version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      runtime-dependencies:
        patterns:
          - "numpy"
          - "pandas"
          - "pyarrow"
      full-environment-dependencies:
        patterns:
          - "scipy"
          - "scikit-learn"
